### ISSUE TITLE
Changing ranks

### ISSUE THREAD

**Issue by ParadoxPlays** [IvanCraft623/RankSystem#11] opened 2022-06-04 04:26 UTC
I set my rank to Admin but now when I try setting it to default rank it doesn't show in chat that I'm newcomer
![Screenshot_20220603-233951_Minecraft](https://user-images.githubusercontent.com/99149310/171983332-9d8db2e0-275c-413a-9ad3-b095c3c6058f.jpg)

**Comment by ParadoxPlays** [comment] 2022-06-04 04:45
Going to guess this is the multi rank per user support. I would suggest that this should be toggable in config because this would get very annoying.

**Comment by ParadoxPlays** [comment] 2022-06-04 04:49
Also make it so we can just set what ranks higher ranks inherit, having multiple ranks per user would get very confusing after some time.

**Comment by IvanCraft623** [comment] 2022-06-08 02:03
> Also make it so we can just set what ranks higher ranks inherit, having multiple ranks per user would get very confusing after some time.

You must remove the Admin rank, this is because this plugin supports multiple ranks at once.

**Comment by NJMD13** [comment] 2022-06-16 23:33
I have a similar problem.

When setting the Guest rank as Default, in Minecraft if the chat appears as Guest but the permissions are not given and I already checked the configuration of the ranks.yml and it is fine, but in the database it does not appear that the user has the rank .

**Comment by xRodzMC** [comment] 2022-06-18 05:48
> I have a similar problem.
> 
> When setting the Guest rank as Default, in Minecraft if the chat appears as Guest but the permissions are not given and I already checked the configuration of the ranks.yml and it is fine, but in the database it does not appear that the user has the rank .

That is depending when player is op, and you have been /deop ,you will removed some permissions, i think, the ranks should be synched when changing like /op and /deop

or your plugin has following concepts:
```yml
permissions:
       test.perms:
              default: op
```

or it might be the mysql problems, try to reproduce it on sqlite.

**Comment by xRodzMC** [comment] 2022-06-18 05:56
> I set my rank to Admin but now when I try setting it to default rank it doesn't show in chat that I'm newcomer ![Screenshot_20220603-233951_Minecraft](https://user-images.githubusercontent.com/99149310/171983332-9d8db2e0-275c-413a-9ad3-b095c3c6058f.jpg)

same thing, this plugin supports multiple ranks. If you have already ranks like admin, it would addition the another rank. Try to remove the admin rank to remove permissions.

**Comment by NJMD13** [comment] 2022-06-18 14:00
I think I didn't know how to make myself understood (I apologize).

The Guest rank is configured as the default rank (that is, it is given to all players who enter the server), but even if the Guest rank has the permissions [pocketmine.command.transferserver and pocketmine.command.say] they cannot use those commands.

To make the permissions work for them, I need to remove and re-give them the Guest rank so they can run the commands.


I apologize again, if I did not understand myself again, but I have never made myself understood well.

**Comment by xRodzMC** [comment] 2022-06-19 12:25
> I think I didn't know how to make myself understood (I apologize).
> 
> The Guest rank is configured as the default rank (that is, it is given to all players who enter the server), but even if the Guest rank has the permissions [pocketmine.command.transferserver and pocketmine.command.say] they cannot use those commands.
> 
> To make the permissions work for them, I need to remove and re-give them the Guest rank so they can run the commands.
> 
> I apologize again, if I did not understand myself again, but I have never made myself understood well.

for fast reading: if players join, the default ranks current permission would give them.

**Comment by IvanCraft623** [comment] 2022-06-19 14:38
> I think I didn't know how to make myself understood (I apologize).
> 
> The Guest rank is configured as the default rank (that is, it is given to all players who enter the server), but even if the Guest rank has the permissions [pocketmine.command.transferserver and pocketmine.command.say] they cannot use those commands.
> 
> To make the permissions work for them, I need to remove and re-give them the Guest rank so they can run the commands.
> 
> I apologize again, if I did not understand myself again, but I have never made myself understood well.

Reproduced

**Comment by xRodzMC** [comment] 2022-06-20 04:02
> > I think I didn't know how to make myself understood (I apologize).
> > The Guest rank is configured as the default rank (that is, it is given to all players who enter the server), but even if the Guest rank has the permissions [pocketmine.command.transferserver and pocketmine.command.say] they cannot use those commands.
> > To make the permissions work for them, I need to remove and re-give them the Guest rank so they can run the commands.
> > I apologize again, if I did not understand myself again, but I have never made myself understood well.
> 
> Reproduced

maybe we can make onJoin() in event listener to sync ranks?

**Comment by IvanCraft623** [comment] 2022-06-21 01:16
Fixed on d45c1ef351cdd36ab717de10d003831dde2c3a3f

**Closed as completed by IvanCraft623** 2022-06-21 01:16 UTC
